---
- name: Audit /etc/sudoers for accounts allowed to run any command anywhere as root
  hosts: all
  gather_facts: false
  tasks:
    - name: Read /etc/sudoers file
      become: true
      slurp:
        src: /etc/sudoers
      register: sudoers_content

    - name: Decode sudoers content
      set_fact:
        sudoers_decoded: "{{ sudoers_content.content | b64decode }}"

    - name: Extract accounts/groups allowed full root access
      set_fact:
        full_root_access_accounts: >-
          {{
            sudoers_decoded.split('\n')
            | select('match', '^([a-zA-Z0-9_-]+|%[a-zA-Z0-9_-]+)\s+ALL=\(ALL(:ALL)?\)\s+ALL')
            | map('regex_search', '^([a-zA-Z0-9_-]+|%[a-zA-Z0-9_-]+)')
            | unique
            | list
          }}

    - name: Show accounts/groups allowed full root access
      debug:
        msg: |
          Host: {{ inventory_hostname }}
          Accounts/Groups allowed to run any command anywhere as root in /etc/sudoers:
          {% for acc in full_root_access_accounts %}
          {{ acc }}
          {% endfor %}
