---
- name: Audit /etc/sudoers and display results on console
  hosts: all
  gather_facts: false
  tasks:
    - name: Read /etc/sudoers file content
      become: true
      slurp:
        src: /etc/sudoers
      register: sudoers_content

    - name: Parse sudoers for root access
      set_fact:
        sudoers_decoded: "{{ sudoers_content.content | b64decode }}"
        root_access_lines: "{{ sudoers_decoded.split('\n') | select('match', '^(root|%[^\s]+)\\s+ALL=\\(ALL(:ALL)?\\)\\s+ALL') | list }}"

    - name: Show users/groups with root access
      debug:
        msg: |
          Host: {{ inventory_hostname }}
          Lines granting root access in /etc/sudoers:
          {% for line in root_access_lines %}
          {{ line }}
          {% endfor %}
