---
- name: Audit /etc/sudoers and get names with root access
  hosts: all
  gather_facts: false
  tasks:
    - name: Read /etc/sudoers file
      become: true
      slurp:
        src: /etc/sudoers
      register: sudoers_content

    - name: Decode /etc/sudoers content
      set_fact:
        sudoers_decoded: "{{ sudoers_content.content | b64decode }}"

    - name: Extract names with root access
      set_fact:
        root_access_names: >-
          {{
            sudoers_decoded.split('\n')
            | select('match', '^(root|%[a-zA-Z0-9_-]+)\\s+ALL=\\(ALL(:ALL)?\\)\\s+ALL')
            | map('regex_search', '^(root|%[a-zA-Z0-9_-]+)')
            | map('regex_replace', '^%', '')
            | unique
            | list
          }}

    - name: Show names with root access
      debug:
        msg: |
          Host: {{ inventory_hostname }}
          Users/Groups with root access in /etc/sudoers:
          {% for name in root_access_names %}
          {{ name }}
          {% endfor %}
