---
- name: Audit /etc/sudoers and get all accounts with root access
  hosts: all
  gather_facts: false
  tasks:
    - name: Read /etc/sudoers file
      become: true
      slurp:
        src: /etc/sudoers
      register: sudoers_content

    - name: Decode /etc/sudoers content
      set_fact:
        sudoers_decoded: "{{ sudoers_content.content | b64decode }}"

    - name: Extract all accounts/groups with root access
      set_fact:
        root_accounts: >-
          {{
            sudoers_decoded.split('\n')
            | select('match', '^([a-zA-Z0-9_-]+|%[a-zA-Z0-9_-]+)\\s+ALL=\\(ALL(:ALL)?\\)\\s+ALL')
            | map('regex_search', '^([a-zA-Z0-9_-]+|%[a-zA-Z0-9_-]+)')
            | map('regex_replace', '^%', '')
            | unique
            | list
          }}

    - name: Show all accounts/groups with root access
      debug:
        msg: |
          Host: {{ inventory_hostname }}
          Accounts/Groups with root access in /etc/sudoers:
          { for account in root_accounts }
          {{ account }}
          {% endfor %}
