---
- name: Check /etc/sudoers for ALL=(ALL) ALL privileges
  hosts: all
  become: true # This playbook needs root privileges to read /etc/sudoers

  tasks:
    - name: Slurp the content of /etc/sudoers
      ansible.builtin.slurp:
        src: /etc/sudoers
      register: sudoers_content

    - name: Decode the base64 content
      ansible.builtin.set_fact:
        decoded_sudoers: "{{ sudoers_content['content'] | b64decode }}"

    - name: Find users with ALL=(ALL) ALL privileges
      ansible.builtin.set_fact:
        privileged_users: [] # Initialize an empty list
      run_once: true # Ensure this fact is set only once per playbook run

    - name: Extract and add privileged users to the list
      ansible.builtin.set_fact:
        privileged_users: "{{ privileged_users + [item | regex_replace('^\\s*([^#\\s]+)\\s+ALL=\\(ALL\\)\\s+ALL.*', '\\1')] }}"
      loop: "{{ decoded_sudoers.splitlines() }}"
      when: item is search('^\\s*([^#\\s]+)\\s+ALL=\\(ALL\\)\\s+ALL')

    - name: Display privileged users
      ansible.builtin.debug:
        msg: "The following users/groups have 'ALL=(ALL) ALL' privileges: {{ privileged_users | unique }}"
      when: privileged_users | length > 0
