- name: Disable specified user accounts
  hosts: all
  become: true

  vars:
    accounts_to_disable:
      - logstash

  tasks:
    - name: Ensure accounts are disabled
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        password_lock: true
        shell: /sbin/nologin
        comment: "Account disabled by Ansible"
      loop: "{{ accounts_to_disable }}"
      ignore_errors: true # Continue if an account does not exist

    - name: Verify account status (optional)
      ansible.builtin.shell: "grep '^{{ item }}:' /etc/passwd"
      register: user_check
      changed_when: false
      loop: "{{ accounts_to_disable }}"

    - name: Display account status
      ansible.builtin.debug:
        msg: "Account {{ item.item }}: {{ item.stdout }}"
      loop: "{{ user_check.results }}"
      when: item.rc == 0
