---
- name: Get all users on Linux hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Get list of users from /etc/passwd
      shell: cut -d: -f1 /etc/passwd
      register: passwd_users

    - name: Show all users
      debug:
        var: passwd_users
