---
- name: Get all users in /etc/passwd and their last login dates
  hosts: all
  gather_facts: false
  tasks:
    - name: Get all usernames from /etc/passwd (all users)
      become: true
      shell: awk -F: '{print $1}' /etc/passwd
      register: all_passwd_users

    - name: Get last login for each user from lastlog
      become: true
      shell: lastlog -u {{ item }}
      register: lastlog_per_user
      loop: "{{ all_passwd_users.stdout_lines }}"
      changed_when: false

    - name: Show user and last login date
      debug:
        msg: |
          Host: {{ inventory_hostname }}
          User: {{ item.stdout_lines[1].split()[0] if item.stdout_lines|length > 1 else 'UNKNOWN' }}
          Last Login: {{ ' '.join(item.stdout_lines[1].split()[1:]) if item.stdout_lines|length > 1 else 'Never logged in' }}
      loop: "{{ lastlog_per_user.results }}"
