---
- name: Get all users and their last login dates on Linux hosts
  hosts: all
  gather_facts: false

  tasks:
    - name: Get list of users from /etc/passwd
      shell: cut -d: -f1 /etc/passwd
      register: passwd_users

    - name: Get last login for each user
      shell: lastlog -u {{ item }} | awk 'NR==2 {print $1, $4, $5, $6, $7, $8, $9}'
      loop: "{{ passwd_users.stdout_lines }}"
      register: user_lastlog
      failed_when: false
      changed_when: false

    - name: Show user and last login
      debug:
        msg: "{{ item.stdout }}"
      loop: "{{ user_lastlog.results }}"
