---
- name: Retrieve all users in /etc/passwd
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Get all usernames from /etc/passwd
      shell: awk -F: '{print $1}' /etc/passwd
      register: passwd_users
      changed_when: false

    - name: Show all users
      debug:
        msg: "{{ passwd_users.stdout_lines }}"
