---
- name: Get all users from /etc/passwd and their login dates
  hosts: all
  become: true

  tasks:
    - name: Get all users from /etc/passwd
      shell: awk -F: '{print $1}' /etc/passwd
      register: passwd_users
      changed_when: false

    - name: Get last login for each user
      shell: lastlog -u {{ item }}
      register: lastlog
      loop: "{{ passwd_users.stdout_lines }}"
      changed_when: false

    - name: Show user and last login date
      debug:
        msg: "{{ item.stdout_lines | join(' ') }}"
      loop: "{{ lastlog.results }}"
